### ISSUE TITLE
GET by the code provider 'code'

### ISSUE THREAD

**Issue by cmsdroff** [bic-org/Facility-Code#1]
SMDG raised that it would be useful to ‘GET’ by just the code assigned i.e. ‘CTA’.  This of course is not unique on its own as it could yield several results in different locations.  SMDG split the code (UNLOCODE + SMDG Identifier) this is useful in the EDIFACT messages as it stops the user repeating the location twice.  For API the combined code would normally be searched for as a complete string.

BIC do not differentiate the 'code' and work on a consolidated code only.

DCSA identify the 'code' of the code provider separately

**Comment by cmsdroff** [comment]
@lewis-david-wong could we consider how this could be achieved, for SMDG this is an important difference, for BIC it is always the combined code.

DCSA reference this as `Code List Provider Code` 

It would be useful to retrieve the requested codes from the API, then apply the logic to shape the response.

```
IF the codeProvider = SMDG
    remove the UNLOCODE (first 5 character from the left) and return the remaining characters in a new field
```

The existing json would be returned as it is now with the following `"codeListProviderCode": "SECT"`

```json
{
  "code": "CNSGHSECT",
  "codeProvider": "SMDG",
  "codeListProviderCode": "SECT",
  "unLocode": "CNSGH",
  "countryCode": "CN",
  "facility": {
    "name": "SHANGHAI EAST CONTAINER TERMINAL (WAIGAOQIAO PHASE 4)",
    "address": {
      "street": "-",
      "city": "-",
      "state": "-",
      "postcode": "-",
      "country": "-"
    },
    "formattedAddress": "-",
    "geographicalCoordinate": {
      "latitude": "-",
      "longitude": "-"
    }
  }
}
```

For BIC the response would either need to contain the complete combined code OR omit the code provider code.  To be discussed.

**Comment by Lewis-David-Wong** [comment]
Example output:

```json
{
  "code": "DEHAMCTA",
  "codeProvider": "SMDG",
  "codeListProviderCode": "CTA",
  "unLocode": "DEHAM",
  "countryCode": "DE",
  "facility": {
    "name": "HHLA CONTAINER TERMINAL ALTENWERDER (CTA)",
    "address": {
      "street": "-",
      "city": "-",
      "state": "-",
      "postcode": "-",
      "country": "-"
    },
    "formattedAddress": "Am Ballinkai 1, 21129 Hamburg, Germany",
    "geographicalCoordinate": {
      "latitude": "53.50083",
      "longitude": "9.93639"
    }
  },
  "operator": {
    "name": "EUROGATE CONTAINER TERMINAL HAMBURG"
  }
}
```

**Comment by cmsdroff** [comment]
From discussion we have decided for now not to apply this endpoint to avoid confusion about the `code` and will review if this discussion is raised again.  All parties involved are just using the combined code currently which is supported by the DCSA Information model and general use in systems
