### ISSUE TITLE
Integrate the SMDG Terminal Codes to automate the update of API

### ISSUE THREAD

**Issue by cmsdroff** [bic-org/Facility-Code#11]
Pull the master branch 'on update' from https://github.com/smdg-org/Terminal-Code-List looking for updates to 'master' branch only and on the file https://github.com/smdg-org/Terminal-Code-List/blob/master/SMDG%20Terminal%20Code%20List.csv

@declanoconnor please create the CI/CD scripts to monitor the above and update the API as per the development ticket

@marklim1 adding you for visibility of when this is done and we will arrange walk through

**Comment by cmsdroff** [comment]
Web hook is ready to add to the SMDG GitHub and process changes to master branch @marklim1 ready to show and test.

**Comment by cmsdroff** [comment]
@marklim1 we just need to enable the web hook on the SMDG repository, need your or Jost assistance as owner.  Sent an email on this topic.

**Comment by marklim1** [comment]
@cmsdroff : Hi David, please let me know what needs to be done.
