### ISSUE TITLE
Unified search endpoints

### ISSUE THREAD

**Issue by Chatissimus** [bic-org/Facility-Code#8]
/facilities/byCountry/{countryCode}/{codeProvider}
/facilities/byLocation/{unLocode}/{codeProvider}

is it possible to plan unified endpoints without codeProvider ?
in my mind the true sprit of this API is to unify BIC/SMDG referential access 

Cedric - CMA

**Comment by cmsdroff** [comment]
@Chatissimus we have the code provider as part of a composite key, there is an important reason for this and that is that both code lists can have codes that are 9 characters so we have to differentiate them to keep them unique and not have a situation where the facility code provider cannot assign the code needed to use in the API.

Also would you know you are looking for sea terminal or a container facility when requesting ?

Open to exploring use case to consider if we need to put in place a solution here, just need to understand the use case to justify the change, please add a user story if you would like to explore further

**Comment by cmsdroff** [comment]
@Chatissimus any thoughts or should I close for now?
