### ISSUE TITLE
Facility Type codification

### ISSUE THREAD

**Issue by Chatissimus** [bic-org/Facility-Code#9]
Hi,

Do you plan to add facility type codification like Terminal, Depot , ...,  defined by DCSA ?

**Comment by cmsdroff** [comment]
Hi @Chatissimus 

Thanks for raising this, its a good question, but one that needs to have some context around and I have raised this with DCSA previously, and I note that the V2 of the shipping information model has updated the definitions and types of Facility which provides less overlap and more clarity.

Consider the below:

**Acme Container Services** operate a container storage yard near to the Port of Liverpool UK.  They have a BIC Facility Code `GBLIVACME` for that fixed location facility. The facility receives empty containers on behalf of the carrier once the import leg is completed as a restitution place so would be `DEPO` in this role.  It also stores containers for the carrier that are fully loaded and await delivery to the importer so would also be `COYA` in this role.

So for the BIC Facility in many cases the facility type will be one or the other (`COYA` or `DEPO`) defined by the movement taking place.  But as the facility is a fixed place with no context or knowledge of the movement this is only known by the carrier performing the movement so should be applied during the tracking event being reported.

It could however be possible to provide both `COYA` and `DEPO` for all BIC Facility codes but it would also be perfectly reasonable to have `COFS` as facilities within the dataset as well, especially in the case of a drop and swap operations.

For this reason it seems to be more logical to focus the Facility Code on identifying the actual facility itself with its characteristics which are common such as name, address, gps etc.

So I open this topic to discussion, what we do want to avoid is a code PER facility type, the code should be issued for the facility, the type of facility is a 1 to many attribute so one facility can have many types.

In addition it maybe a challenge to update these types on a global scale with reliability in a repeatable way and this is something that should be considered so not to introduce data quality issues into the code lists, it needs to be available for all.

For all reading the latest definitions on Facility Types defined by DCSA can be found at https://dcsa.org/wp-content/uploads/2020/07/DCSA-Information-model-2.0-vF.pdf on page 36.

**Comment by cmsdroff** [comment]
Hi @Chatissimus 

I discussed this further with the DCSA recently, we have put a pull request into their repo as the facility type mentioned in the information model see PR https://github.com/dcsaorg/DCSA-Information-Model/pull/65 for details of this change.

so closing this topic for now as BIC will provide the code and location details, the facility type to be defined in the transport call.
